### ISSUE TITLE
Complete all processes for code contribution

### ISSUE THREAD

**Issue by Wusong-Fang** [zowe/zowe-chat#7]
Complete all processes for code contribution

- [x] Wicked proposal is approved
- [x] - Finish  internal code scan
- [x] - Move common bot framework code to Zowe Chat repo
- [x] - Finish OMP code scan

**Comment by Joe-Winchester** [comment]
related to #2

**Comment by MarkAckert** [comment]
Complete.
