### ISSUE TITLE
Overall command logic for Zowe Chat

### ISSUE THREAD

**Issue by TingXieIBM** [zowe/zowe-chat#89]
- [ ] Investigate the better solution

- [ ] command syntax design

- [ ]  update framework if it is needed

**Comment by Wusong-Fang** [comment]
* General Command Format: `<scope> <resource> <action> <object> [adjectives]`
  Note: `adjectives = Positional Arguments + Options`
* Scope for Zowe CLI commands: `zowe`
* Scope for Zowe Chat its own commands: `zos`

**Comment by Wusong-Fang** [comment]
- Zowe CLI command will be run natively on Zowe Chat server once Zowe CLI is installed there.
- Zowe Chat its own command style and syntax will be tracked in another issue: https://github.com/zowe/zowe-chat/issues/113
So close the issue.
